upstream gunicorn_helenai_server {
    # For a TCP configuration:
    server 127.0.0.1:9154 fail_timeout=0;
}


server {
    listen 80;
    client_max_body_size 500m;
    server_name helenai.repsys.com.br;
    keepalive_timeout 5;

    location /static/ {
        expires max;
        alias /webapps/helenai_server/helenai_server/static/;
    }

    location /media/ {
        expires max;
        alias /webapps/helenai_server/helenai_server/media/;
    }

    location /assets/ {
        expires max;
        alias /webapps/helenai_server/helenai_server/HelenAI/prototipos/assets/;
    }

    location /pdfs/ {
        expires 1h;
        alias /webapps/helenai_server/helenai_server/HelenAI/pdfs/;
    }

    location / {
        client_max_body_size 500M;
        try_files $uri @proxy_to_app;
    }

    location @proxy_to_app {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        # proxy_redirect off;
        proxy_pass http://gunicorn_helenai_server;
        proxy_connect_timeout 1200;
        proxy_send_timeout 1200;
        proxy_read_timeout 1200;
    }

}
