[program:helenai_server]
command=/webapps/helenai/bin/gunicorn HelenAI.wsgi -t 12000 -b 127.0.0.1:9154 -w2 --pythonpath=/webapps/helenai/backend
user=root
autostart=true
autorestart=true
redirect_stderr=True
