[program:helenai_server]
command=/webapps/helenai_server/bin/gunicorn HelenAI.wsgi -t 12000 -b 127.0.0.1:9154 -w2 --pythonpath=/webapps/helenai_server/helenai_server
user=root
autostart=true
autorestart=true
redirect_stderr=True
; stdout_logfile=/var/log/supervisor/helenai_server.log
; stderr_logfile=/var/log/supervisor/helenai_server_error.log
; stdout_logfile_maxbytes=50MB
; stdout_logfile_backups=5
; stderr_logfile_maxbytes=50MB
; stderr_logfile_backups=5
