[program:form_manager]
command=/webapps/form_manager/bin/gunicorn form_manager.wsgi -t 12000 -b 127.0.0.1:9100 -w2 --pythonpath=/webapps/form_manager/form_manager
user=root
autostart=true
autorestart=true
redirect_stderr=True
; stdout_logfile=/var/log/supervisor/controleinterno_old.log
; stderr_logfile=/var/log/supervisor/controleinterno_old_error.log
; stdout_logfile_maxbytes=50MB
; stdout_logfile_backups=5
; stderr_logfile_maxbytes=50MB
; stderr_logfile_backups=5
